//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int Id { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Player Player { get; set; }
    }
}
