//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerBio
    {
        public int Id { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
